# 1. Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np

In [2]:
mt1=np.matrix([[1,2,3],[4,5,6],[6,7,8]])
mt1

matrix([[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]])

In [3]:
mt2=np.matrix([[9,2,6],[4,2,7],[3,9,1]])
mt2

matrix([[9, 2, 6],
        [4, 2, 7],
        [3, 9, 1]])

In [10]:
mt1+mt2     ## addition of two matrices mt1 and mt2

matrix([[10,  4,  9],
        [ 8,  7, 13],
        [ 9, 16,  9]])

# 2. Write a Python Program to Multiply Two Matrices?

In [9]:
mt1*mt2

matrix([[ 26,  33,  23],
        [ 74,  72,  65],
        [106,  98,  93]])

# 3. Write a Python Program to Transpose a Matrix?

In [13]:
# before Transpose
mt1

matrix([[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]])

In [11]:
# After Transpose
mt1.T

matrix([[1, 4, 6],
        [2, 5, 7],
        [3, 6, 8]])

# 4. Write a Python Program to Sort Words in Alphabetic Order?

In [70]:
def SortWords():
    s = input("Enter a String: ").lower()
    st = sorted(s.split(' '))
    print(' '.join(st))

SortWords()

Enter a String: THIs is A brand new day
a brand day is new this


# 5. Write a Python Program to Remove Punctuation From a String?

In [81]:
def RemovePunctuation():
    s=input("enter a string: ")
    string=''
    punctuations = '''?@#$%^&*_~!()-[]{};:'"\,<>./'''
    for i in s:
        if i not in punctuations:
            string+=i
    print(string)        
    
RemovePunctuation()            

enter a string: I! meant ;to' be" bach /
I meant to be bach 
